
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
public class login extends javax.swing.JFrame {

  

    /**
     * Creates new form login
     */
   
    public login() {
        initComponents();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnlogin = new javax.swing.JPanel();
        loginname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginpass = new javax.swing.JPasswordField();
        logbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("login");

        btnlogin.setBackground(new java.awt.Color(255, 255, 255));
        btnlogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btnlogin.add(loginname, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 233, 31));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\images.jpeg")); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnlogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 37, 31));

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\1200x630wa.png")); // NOI18N
        jLabel3.setText("jLabel2");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnlogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 37, 31));

        loginpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginpassActionPerformed(evt);
            }
        });
        btnlogin.add(loginpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 233, 32));

        logbtn.setBackground(new java.awt.Color(51, 153, 255));
        logbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logbtn.setForeground(new java.awt.Color(0, 0, 102));
        logbtn.setText("Login");
        logbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logbtnActionPerformed(evt);
            }
        });
        btnlogin.add(logbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 124, 34));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("LOGIN FORM");
        btnlogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        btnlogin.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot_20230218_102413.png"))); // NOI18N
        btnlogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnlogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnlogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logbtnActionPerformed
        // TODO add your handling code here:
           //start the login process
           if(loginname.getText().trim().isEmpty() || loginpass.getText().trim().isEmpty())
           {
             JOptionPane.showMessageDialog(null,"username or password should not be empty");  
             
           }
           else{
            try {
            // TODO code application logic here
            Class.forName("com.mysql.cj.jdbc.Driver");
            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbms1","root","allah@01");
                System.out.print(con);
                System.out.print("sucessfull");
               String sql="select *from reg  where user_name=? and pass=?";
               PreparedStatement pstmt = con.prepareStatement(sql);
               pstmt.setString(1,loginname.getText());
               pstmt.setString(2,loginpass.getText());
               ResultSet rs = pstmt.executeQuery();
               if(rs.next()){
               // TODO add your handling code here:
               
             
            
         
           
         desktop ds = new desktop();
         ds.show();             //display login page

         dispose();
               }else{
                    JOptionPane.showMessageDialog(null,"username or password doesnt match");
                loginname.setText("");
                loginpass.setText("");
               }
               
               
               pstmt.executeUpdate();
               JOptionPane.showMessageDialog(null,"registration sucessfull");
           
          
          

            } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null,ex);
            }
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null,e);
        }
           }
 
    }//GEN-LAST:event_logbtnActionPerformed

    private void loginpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginpassActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
           dashboard ds = new dashboard();
             ds.show();             //display login page 
        
        
        dispose();//close current frame after open login page 
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnlogin;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton logbtn;
    private javax.swing.JTextField loginname;
    private javax.swing.JPasswordField loginpass;
    // End of variables declaration//GEN-END:variables

}

